### Inicializando las librerias a ocupar ###

In [4]:
import pyarrow.parquet as pq
import gcsfs
import pandas as pd
from pandas_gbq import to_gbq
import bigframes.pandas as bpd
import json
from google.cloud import storage
from google.oauth2 import service_account
from google.cloud import bigquery
from google.api_core.exceptions import NotFound


PROJECT_ID = 'acme-987654'
LOCATION = "southamerica-east1" 
service_account_path = 'C:/Data/json/acme-987654-c052039ac4cd.json'

bucket_name = "acme_storage"

dataset_raw = "Raw"
dataset_curated = "Curated"

table_checkin_id = "CheckIn"
table_user_id = "User" 
table_business_id = "Business"
table_review_id ="Review"
table_sitios_id = "Sitios"

table_estados_california_id = "Sitios_California"
table_estados_carolina_id = "Sitios_Carolina_Sur"
table_estados_florida_id = "Sitios_Florida"
table_estados_Massachusetts_id = "Sitios_Massachusetts"
table_estados_Texas_id = "Sitios_Texas"
table_estados_Washington_id = "Sitios_Washington"
table_estados_Luisiana_id = "Sitios_Luisiana"

### Librerias a instalar ###

In [48]:
#pip install bigframes
#pip install pandas-gbq
#pip install google-cloud-bigquery
#pip install  --upgrade bigframes

### Información BIG QUERY

In [3]:
from functionBigQuery import etl_estados_json_file

# California

##### Carga estatica de varios archivos por Ciudades

In [4]:
etl_estados_json_file('Google/Estados/California/1.json')
etl_estados_json_file('Google/Estados/California/2.json')
etl_estados_json_file('Google/Estados/California/3.json')
etl_estados_json_file('Google/Estados/California/4.json')
etl_estados_json_file('Google/Estados/California/5.json')
etl_estados_json_file('Google/Estados/California/6.json')
etl_estados_json_file('Google/Estados/California/7.json')
etl_estados_json_file('Google/Estados/California/8.json')
etl_estados_json_file('Google/Estados/California/9.json')
etl_estados_json_file('Google/Estados/California/10.json')
etl_estados_json_file('Google/Estados/California/11.json')
etl_estados_json_file('Google/Estados/California/12.json')
etl_estados_json_file('Google/Estados/California/13.json')
etl_estados_json_file('Google/Estados/California/14.json')
etl_estados_json_file('Google/Estados/California/15.json')
etl_estados_json_file('Google/Estados/California/16.json')
etl_estados_json_file('Google/Estados/California/17.json')
etl_estados_json_file('Google/Estados/California/18.json')

DF Estados no esta vacio, tiene:  (369, 18)
Project is:  acme-987654
Table `acme-987654.Curated.Estados` does not exist.
DF Estados no esta vacio, tiene:  (362, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (469, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (337, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (494, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (223, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (330, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (550, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (965, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (483, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1149, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (335, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2629, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2361, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1441, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2436, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2339, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1781, 18)
Project is:  acme-987654
Update and insert successful!

# Carolina Sur

In [5]:
etl_estados_json_file('Google/Estados/Carolia_Sur/1.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/2.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/3.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/4.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/5.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/6.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/7.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/8.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/9.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/10.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/11.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/12.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/13.json')
etl_estados_json_file('Google/Estados/Carolia_Sur/14.json')

DF Estados no esta vacio, tiene:  (686, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (4913, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (6463, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1551, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1477, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1175, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(

# FLORIDA

In [6]:
etl_estados_json_file('Google/Estados/Florida/1.json')
etl_estados_json_file('Google/Estados/Florida/2.json')
etl_estados_json_file('Google/Estados/Florida/3.json')
etl_estados_json_file('Google/Estados/Florida/4.json')
etl_estados_json_file('Google/Estados/Florida/5.json')
etl_estados_json_file('Google/Estados/Florida/6.json')
etl_estados_json_file('Google/Estados/Florida/7.json')
etl_estados_json_file('Google/Estados/Florida/8.json')
etl_estados_json_file('Google/Estados/Florida/9.json')
etl_estados_json_file('Google/Estados/Florida/10.json')
etl_estados_json_file('Google/Estados/Florida/11.json')
etl_estados_json_file('Google/Estados/Florida/12.json')
etl_estados_json_file('Google/Estados/Florida/13.json')
etl_estados_json_file('Google/Estados/Florida/14.json')
etl_estados_json_file('Google/Estados/Florida/15.json')
etl_estados_json_file('Google/Estados/Florida/16.json')
etl_estados_json_file('Google/Estados/Florida/17.json')
etl_estados_json_file('Google/Estados/Florida/18.json')
etl_estados_json_file('Google/Estados/Florida/19.json')

DF Estados no esta vacio, tiene:  (255, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (448, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (535, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (439, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (498, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (353, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (821, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1314, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1809, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (710, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1852, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2838, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1016, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1316, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2074, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (966, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1258, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (608, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1277, 18)
Project is:  acme-987654
Update and insert successful!

# Massachusetts

In [7]:
etl_estados_json_file('Google/Estados/Massachusetts/1.json')
etl_estados_json_file('Google/Estados/Massachusetts/2.json')
etl_estados_json_file('Google/Estados/Massachusetts/3.json')
etl_estados_json_file('Google/Estados/Massachusetts/4.json')
etl_estados_json_file('Google/Estados/Massachusetts/5.json')
etl_estados_json_file('Google/Estados/Massachusetts/6.json')
etl_estados_json_file('Google/Estados/Massachusetts/7.json')
etl_estados_json_file('Google/Estados/Massachusetts/8.json')
etl_estados_json_file('Google/Estados/Massachusetts/9.json')
etl_estados_json_file('Google/Estados/Massachusetts/10.json')
etl_estados_json_file('Google/Estados/Massachusetts/11.json')
etl_estados_json_file('Google/Estados/Massachusetts/12.json')
etl_estados_json_file('Google/Estados/Massachusetts/13.json')
etl_estados_json_file('Google/Estados/Massachusetts/14.json')
etl_estados_json_file('Google/Estados/Massachusetts/15.json')
etl_estados_json_file('Google/Estados/Massachusetts/16.json')

DF Estados no esta vacio, tiene:  (1266, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2047, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (6230, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2238, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2367, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (971, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(

# TEXAS

In [8]:
etl_estados_json_file('Google/Estados/Texas/1.json')
etl_estados_json_file('Google/Estados/Texas/2.json')
etl_estados_json_file('Google/Estados/Texas/3.json')
etl_estados_json_file('Google/Estados/Texas/4.json')
etl_estados_json_file('Google/Estados/Texas/5.json')
etl_estados_json_file('Google/Estados/Texas/6.json')
etl_estados_json_file('Google/Estados/Texas/7.json')
etl_estados_json_file('Google/Estados/Texas/8.json')
etl_estados_json_file('Google/Estados/Texas/9.json')
etl_estados_json_file('Google/Estados/Texas/10.json')
etl_estados_json_file('Google/Estados/Texas/11.json')
etl_estados_json_file('Google/Estados/Texas/12.json')
etl_estados_json_file('Google/Estados/Texas/13.json')
etl_estados_json_file('Google/Estados/Texas/14.json')
etl_estados_json_file('Google/Estados/Texas/15.json')
etl_estados_json_file('Google/Estados/Texas/16.json')

DF Estados esta vacio :(
DF Estados no esta vacio, tiene:  (23, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (28, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (70, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (5, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (10, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (25, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados no esta vacio, tiene:  (12, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados no esta vacio, tiene:  (413, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(

# Washington

In [9]:
etl_estados_json_file('Google/Estados/Washington/1.json')
etl_estados_json_file('Google/Estados/Washington/2.json')
etl_estados_json_file('Google/Estados/Washington/3.json')
etl_estados_json_file('Google/Estados/Washington/4.json')
etl_estados_json_file('Google/Estados/Washington/5.json')
etl_estados_json_file('Google/Estados/Washington/6.json')
etl_estados_json_file('Google/Estados/Washington/7.json')
etl_estados_json_file('Google/Estados/Washington/8.json')
etl_estados_json_file('Google/Estados/Washington/9.json')
etl_estados_json_file('Google/Estados/Washington/10.json')
etl_estados_json_file('Google/Estados/Washington/11.json')
etl_estados_json_file('Google/Estados/Washington/12.json')
etl_estados_json_file('Google/Estados/Washington/13.json')

DF Estados no esta vacio, tiene:  (1605, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2007, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2108, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (5658, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (6909, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2098, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (2871, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (3604, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (3381, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(

# Luisiana

In [10]:
etl_estados_json_file('Google/Estados/Luisiana/1.json')
etl_estados_json_file('Google/Estados/Luisiana/2.json')
etl_estados_json_file('Google/Estados/Luisiana/3.json')
etl_estados_json_file('Google/Estados/Luisiana/4.json')
etl_estados_json_file('Google/Estados/Luisiana/5.json')
etl_estados_json_file('Google/Estados/Luisiana/6.json')
etl_estados_json_file('Google/Estados/Luisiana/7.json')
etl_estados_json_file('Google/Estados/Luisiana/8.json')
etl_estados_json_file('Google/Estados/Luisiana/9.json')
etl_estados_json_file('Google/Estados/Luisiana/10.json')

DF Estados no esta vacio, tiene:  (864, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (7099, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (6850, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (1847, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados no esta vacio, tiene:  (375, 18)
Project is:  acme-987654
Update and insert successful!
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(
DF Estados esta vacio :(

##### Obtener dataframe de big query

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [11]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("Estados", "name, user_id")
df.head(5)

        SELECT name, user_id FROM acme-987654.Curated.Estados

          name                user_id
0  Juana Deisy  109930874857448399288
1    Patrick D  106182812215193337035
2        Nik P  101973906865739080972
3           GM  114236668567198167674
4  Ron Mallard  104339582850059257678

# SITIOS

In [1]:
from functionBigQuery import etl_sitios_json_file

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
etl_sitios_json_file('Google/Sitios/2.json')

QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city)

Update and insert successful!

In [2]:
etl_sitios_json_file('Google/Sitios/1.json') 
etl_sitios_json_file('Google/Sitios/2.json') 
etl_sitios_json_file('Google/Sitios/3.json') 
etl_sitios_json_file('Google/Sitios/4.json') 
etl_sitios_json_file('Google/Sitios/5.json') 
etl_sitios_json_file('Google/Sitios/6.json') 
etl_sitios_json_file('Google/Sitios/7.json') 
etl_sitios_json_file('Google/Sitios/8.json') 
etl_sitios_json_file('Google/Sitios/9.json') 
etl_sitios_json_file('Google/Sitios/10.json') 
etl_sitios_json_file('Google/Sitios/11.json')

QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Table `acme-987654.Curated.Sitios` does not exist.
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 1 0]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 1 0]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!
QUe valores tenemos  [2 0 1]
Project is:  acme-987654
query is:
        MERGE `acme-987654.Curated.Sitios` AS target
        USING `acme-987654.Raw.Sitios` AS source
        ON target.gmap_id = source.gmap_id
            and target.address = source.address
            and target.name = source.name
            and target.latitude = source.latitude
            and target.longitude = source.longitude
            and target.city = source.city
            and target.state = source.state
            and target.category = source.category
        WHEN MATCHED THEN
            UPDATE SET
            target.avg_rating = source.avg_rating,
            target.num_of_reviews = source.num_of_reviews,
            target.is_seafood = source.is_seafood
        WHEN NOT MATCHED THEN
            INSERT (name, address, gmap_id, description, latitude, longitude, category, avg_rating, num_of_reviews, hours, MISC, state, city,is_seafood)
            VALUES (source.name, source.address, source.gmap_id, source.description, source.latitude, source.longitude, source.category, source.avg_rating, source.num_of_reviews, source.hours, source.MISC, source.state, source.city, source.is_seafood)

Update and insert successful!

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [2]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("Sitios", "*")
df.head(5)

        SELECT * FROM acme-987654.Curated.Sitios

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,hours,MISC,state,is_seafood,city
0,Emerald Express,"Emerald Express, 3225 N Harbor Dr, San Diego, ...",0x80deab1606317a29:0x87cd3d1989f69ffb,"Laid-back Chinese eatery offering seafood, dim...",32.732497,-117.197728,['Chinese restaurant'],2.7,58,"[['Tuesday', '10AM–10PM'], ['Wednesday', '10AM...","{'Service options': ['Delivery'], 'Payments': ...",ca,<NA>,san diego
1,Goody Goody,"Goody Goody, Tampa International Airport, Airs...",0x88c2c3e44b23fead:0xf289e5892c2343e7,None,27.982041,-82.532096,"['American restaurant', 'Restaurant']",2.2,17,"[['Sunday', '5AM–9PM'], ['Monday', '5AM–9PM'],...","{'Service options': ['Takeout', 'Delivery'], '...",fl,<NA>,tampa
2,Exotica Mundial International,"Exotica Mundial International, 4950 54th St, S...",0x80d95429b64a8e27:0x7bc226564cd48e68,None,32.767863,-117.080975,None,1.0,1,None,None,ca,<NA>,san diego
3,Clean Water Action,"Clean Water Action, 262 Washington St # 601, B...",0x89e3708465876107:0x6022a27f95390aa0,None,42.358006,-71.052372,None,1.0,1,None,None,ma,<NA>,boston
4,Carvel Express,"Carvel Express, 61 Boston Turnpike, Shrewsbury...",0x89e4088638b3ef13:0x5a990cdd35595daa,Circa-1934 chain known for its soft-serve ice ...,42.275377,-71.752097,"['Ice cream shop', 'Bakery', 'Cake shop', 'Des...",1.0,6,None,"{'Service options': ['Delivery'], 'Accessibili...",ma,<NA>,boston

# Checkin

#### Código insertar en la tabla de Checkin

In [9]:
from functionBigQuery import etl_checkin_json_file
etl_checkin_json_file('Yelp/checkin.json')

Project is:  acme-987654
Update and insert successful!

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [4]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("CheckIn", "*")
df.head(5)

        SELECT * FROM acme-987654.Curated.CheckIn

              business_id                                               date
0  -ICXSJvzmjq0yKdI3xkBfQ                              [2013-04-25 16:17:10]
1  0LXdnyZy4ae8J28Ckjvv7w  [2020-01-23 20:30:25, 2020-01-31 22:45:09, 202...
2  0daUZ2jQ6QvMSd1N1BzrYw  [2015-08-24 14:36:51, 2015-10-19 14:05:16, 201...
3  2HD88VjLfRjo2jRwfZ_q-w  [2011-03-17 20:54:35, 2011-07-02 17:53:27, 201...
4  2qOEIzD_d5VEOzFWgvDUkQ  [2012-02-15 00:09:34, 2012-09-07 21:53:24, 201...

# Business

In [10]:
from functionBigQuery import etl_business_file
etl_business_file('gs://acme_storage/Yelp/business.pkl')

Project is:  acme-987654
Update and insert successful!

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [1]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("Business", "*")
df.head(5)

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

        SELECT * FROM acme-987654.Curated.Business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,8qO7zrY_pTvsk7-UFST2hA,PODS,,Clearwater,DE,,32.322172,-110.967568,1.0,7,1,None,"Packing Supplies, Local Services, Home Service...",None
1,N9S8P_ff8ERsqzpyvK-pUw,Philadelphia Guitar Instruction,,Philadelphia,NV,,39.952335,-75.163789,1.0,5,1,{'RestaurantsPriceRange2': '1'},"Shopping, Musical Instruments & Teachers",None
2,bvEUl7fRuShNr_befCDUNg,Storage Squad,,Nashville,AZ,,36.162664,-86.781602,1.0,8,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Movers","{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ..."
3,jTV9aFLqt6ARVwW_UPdtig,US Concrete Curbing,,Tampa,IN,,27.950575,-82.457178,1.0,7,1,None,"Masonry/Concrete, Landscaping, Home Services, ...",None
4,gRcz0TU5GAeF2j72eJqOrw,Done Right Moving,,Edmonton,AB,,53.544389,-113.490927,1.0,7,1,{'ByAppointmentOnly': 'True'},"Movers, Home Services",None

# Review

In [1]:
from functionBigQuery import etl_review_json_file
etl_review_json_file('Yelp/review.json')

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

Project is:  acme-987654

BadRequest: 400 Syntax error: Unexpected "=" at [6:32]; reason: invalidQuery, location: query, message: Syntax error: Unexpected "=" at [6:32]

Location: US
Job ID: 600f9958-af51-45a0-ad40-c1849d156c86

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [1]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("Review", "*")
df.head(5)

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

        SELECT * FROM acme-987654.Curated.Review

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,hwLdmE_c1-Z7mvXtFYpY0w,Rb5njyroPAefYfoj6kQyfw,gK3QuWCj2a_dr-MVaO1g5A,1.0,0,0,0,I've never heard so many excuses on why they s...,2019-04-13 03:09:34
1,fRRTWI6MhRZ2kAMPO4pHZg,6YFDStKewRiXI9BMESYLQg,AaTpjyw-EiODgi3tR4Xr-g,1.0,0,0,0,Did restaurant week here last night. I did the...,2020-01-19 01:46:53
2,zBqftUqaOQz1lr1LaWYJZw,oZZqkp-aty5PngMefKvPtw,NuI532ndKlcbevcw68YCRA,1.0,1,0,0,Not accommodating for large parties. Carissa w...,2015-03-20 21:01:32
3,a3JZq9I_EjgJfW3nKj3FGw,ulgHLqU7o0fngKLbxDNH7g,tr3JqyQpKJdzJpGtQ6brnQ,1.0,1,0,0,I would have loved to try their services but c...,2018-08-23 19:09:31
4,vhHI0n4Gs97emskKTputOQ,0S_i96G5FR7oYO3QeH_01Q,2HaMlRfOfVLpArXnCQr2Ow,1.0,4,0,0,"For as awesome as the King of Prussia Mall is,...",2011-02-07 00:57:37

# TIP

In [1]:
from functionBigQuery import etl_tip_json_file
etl_tip_json_file('Yelp/tip.json')

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

Project is:  acme-987654

        MERGE `acme-987654.Curated.Tip` AS target
        USING `acme-987654.Raw.Tip` AS source
            ON target.user_id = source.user_id
            and target.business_id = source.business_id
            and target.date = source.date
            and target.text = source.text
        WHEN MATCHED THEN
            UPDATE SET target.compliment_count = source.compliment_count
        WHEN NOT MATCHED THEN
            INSERT (user_id, business_id, text, date, compliment_count)
            VALUES (source.user_id, source.business_id, source.text, source.date, source.compliment_count)

Update and insert successful!

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [2]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("Tip", "*")
df.head(5)

        SELECT * FROM acme-987654.Curated.Tip

,user_id,business_id,text,date,compliment_count
0,St3aCytjxiMN-5OvFvcgSw,---kPU91CF4Lq2-WlRu9Lw,Great food & service!! Crab cakes were excell...,2021-09-23 16:58:31,0
1,zmgsdGzOp08BWJZ2yrOKww,---kPU91CF4Lq2-WlRu9Lw,Awesome raw bar /fish shack. Exactly how I liv...,2021-12-03 18:35:53,0
2,VjvrRYcqu34DyBns0R11bg,---kPU91CF4Lq2-WlRu9Lw,Excellent,2021-01-12 23:10:44,0
3,VjvrRYcqu34DyBns0R11bg,---kPU91CF4Lq2-WlRu9Lw,Great place! Excellent Food!,2021-03-30 03:53:21,0
4,DPSY6qV8RmQZ_XlIjIw_SA,--0iUa4sNDFiZFrAdIWhZQ,Gets crowded the weekend so just order ahead o...,2009-07-30 15:13:31,0

# User

In [1]:
from functionBigQuery import etl_user_file
etl_user_file('gs://acme_storage/Yelp/user.parquet')

[nltk_data] Downloading package vader_lexicon to C:\Users\DELIA
[nltk_data]     MONTOYA\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

BadRequest: 400 Syntax error: Expected keyword WHEN but got keyword TARGET at [15:9]; reason: invalidQuery, location: query, message: Syntax error: Expected keyword WHEN but got keyword TARGET at [15:9]

Location: US
Job ID: 88da6234-72e7-4ac0-9d5a-e985157b856d

Agrega las columnas separadas por coma o asterisco (*) para traer todo la información

In [3]:
from functionBigQuery import get_table_curated_by_columns
df = get_table_curated_by_columns("User", "*")
df.head(5)

        SELECT * FROM acme-987654.Curated.User

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,average_stars,num_amigos,fue_elite_2015,total_compliment
0,uuaHtv7mPH-YsuVANFRiKg,Alex,19,2020-01-14 01:46:04,6,1,0,,None,0,3.89,1,False,0
1,lwqczHV-z_X3w6xLKzFUMA,Kat,8,2018-07-23 16:47:30,7,1,2,,EavLLGSFMRdzhD9qSb8WqQ,0,4.00,1,False,0
2,go7zeOzGlDflVhflXWer7Q,Nash,30,2012-06-28 15:17:20,11,3,3,,"tsig-IJlwoLb7mVhe2ZJxQ, 7aFkRlqgQeTxr1FmzuH_cQ...",1,3.97,350,False,1
3,-PTLcH9vw_MnrCQNiIYQQw,Lien,13,2012-09-27 15:48:28,8,2,3,,J-ZKA_LWI_C1T3JtyEgNuA,0,4.31,1,False,1
4,62DrXi03BLN_zCwWe1-m6Q,Del,5,2012-10-17 14:53:40,9,2,2,,"q4OPFTPQOFoXNqENqPoVGA, nQhmJLaxHY6RBNnK4RGvpw...",1,4.50,703,False,4